name: Analyze Workflow Logs

on:
  workflow_dispatch: 
    inputs:
      triggered_by:
        description: 'Who triggered the analysis'
        required: false
        default: 'lambda'

jobs:
  log-collector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run log collector
        run: |
          go run main.go
          ls -l logs/unzipped/
          echo "Log collection completed."
          echo "Logs are available in the 'logs/unzipped/' directory."
          echo "Printing the contents of the directory:"
          cat logs/unzipped/*.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
